# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200309_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecord',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roots', to='app01.CommentRecord', verbose_name='根评论'),
        ),
        migrations.AlterField(
            model_name='commentrecord',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='app01.CommentRecord', verbose_name='回复'),
        ),
    ]
