# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200314_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=64, verbose_name='详细图')),
                ('carousel', models.BooleanField(default=False, verbose_name='是否在轮播中显示')),
                ('order', models.FloatField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name_plural': '拍品详细图',
            },
        ),
        migrations.CreateModel(
            name='DepositRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未支付'), (2, '支付成功')], default=1, verbose_name='状态')),
                ('uid', models.CharField(max_length=64, verbose_name='流水号')),
                ('deposit_type', models.SmallIntegerField(choices=[(1, '单品保证金'), (2, '全场保证金')], verbose_name='保证金类型')),
                ('pay_type', models.SmallIntegerField(choices=[(1, '微信'), (2, '余额')], verbose_name='支付方式')),
                ('amount', models.PositiveIntegerField(verbose_name='金额')),
            ],
        ),
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name_plural': '拍卖系列'},
        ),
        migrations.AlterModelOptions(
            name='auctionitem',
            options={'verbose_name_plural': '拍品'},
        ),
        migrations.AlterModelOptions(
            name='auctionitemdetail',
            options={'verbose_name_plural': '拍品规格'},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='img',
        ),
        migrations.RemoveField(
            model_name='auctionitem',
            name='img',
        ),
        migrations.RemoveField(
            model_name='auctionitemdetail',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='auctionitemdetail',
            name='img',
        ),
        migrations.RemoveField(
            model_name='auctionitemdetail',
            name='order',
        ),
        migrations.AddField(
            model_name='auction',
            name='cover',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='auction',
            name='deposit',
            field=models.PositiveIntegerField(default=1000, verbose_name='全场保证金'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='cover',
            field=models.CharField(default='', max_length=128, verbose_name='拍品封面'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='start_price',
            field=models.PositiveIntegerField(default=0, verbose_name='起拍价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionitemdetail',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app01.AuctionItem', verbose_name='拍品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionitemdetail',
            name='key',
            field=models.CharField(default=0, max_length=16, verbose_name='项'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionitemdetail',
            name='value',
            field=models.CharField(default=0, max_length=32, verbose_name='值'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未开拍'), (2, '预展中'), (3, '拍卖中'), (4, '已结束')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Auction', verbose_name='拍卖专场'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='deposit',
            field=models.PositiveIntegerField(default=100, verbose_name='单品保证金'),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '待拍卖'), (2, '预展中'), (3, '拍卖中'), (4, '成交'), (5, '流拍')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='bidrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '竞价'), (2, '成交'), (3, '逾期未付款')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Auction', verbose_name='拍卖专场'),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.AuctionItem', verbose_name='拍品'),
        ),
        migrations.AddField(
            model_name='depositrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='auctionitemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.AuctionItem', verbose_name='拍品'),
        ),
    ]
