# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200317_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.PositiveIntegerField(default=1000, verbose_name='余额'),
        ),
    ]
